language: rust
sudo: required
cache: cargo
services:
  - postgresql

dist: trusty
os:
  - linux
    
addons:
  apt:
    packages:
      - libssl-dev
      - libpq-dev

rust:
  - nightly

matrix:
  allow_failures:
    - rust: nightly

before_script:
  - cargo clean
  - psql -c 'create database dbtest;' -U postgres
  - echo "DATABASE_URL=postgres://postgres@localhost/dbtest" > .env
  - cargo install diesel_cli --no-default-features --features=postgres --force
  - diesel migration run

script:
  - cargo build --verbose --all
  - cargo test --verbose --all
  
after_success: |
  RUSTFLAGS="--cfg procmarco2_semver_exempt" cargo install cargo-tarpaulin
  cargo tarpaulin --out Xml
  bash <(curl -s https://codecov.io/bash)
