language: rust
sudo: required
cache: cargo
dist: trusty
os:
  - linux
    
addons:
  apt:
    packages:
      - libssl-dev
      - libpq-dev

rust:
  - nightly

matrix:
  allow_failures:
    - rust: nightly

script:
  - cargo clean
  - cargo build
  - cargo test
  
after_success: |
  RUSTFLAGS="--cfg procmarco2_semver_exempt" cargo install cargo-tarpaulin
  cargo tarpaulin --out Xml
  bash <(curl -s https://codecov.io/bash)
